apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wego-http-server.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "wego-http-server.selectorLabels" . | nindent 6 }}
