apiVersion: v1
kind: Service
metadata:
  name: {{ include "wego-http-server.fullname" . }}
spec:
  selector:
    {{- include "wego-http-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
